version: '3.4'
services:
  db:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongodb_data:/data/db
    environment:
      - ./mongo.env
  # node:
  #   depends_on:
  #     - db
  #   image: node:latest
  #   volumes:
  #     - ./:./app
  #   expose:
  #     - 8080:8080
  #   command: npm start